version: '3.6'

services:

  rate_limit_redis:
    image: redis:7-alpine
    container_name: rate_limit_redis
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
      interval: 5s
      timeout: 10s
      retries: 10
