name: Run Pull Request label check

on:
  pull_request:
    types: [opened, labeled, unlabeled, ready_for_review, reopened, synchronize]
    branches: [main]

jobs:
  label-check:
    name: Check if correct labels are added
    runs-on: ubuntu-latest
    steps:
      - name: Check PR labels added
        uses: mheap/github-action-required-labels@v5
        with:
          mode: exactly
          count: 1
          labels: "patch, minor, major"
          exit_type: failure
          token: ${{ secrets.GITHUB_TOKEN }}
